version: "2"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mariadb
    volumes:
      - "./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: always

  nginx:
    depends_on:
      - phpfpm
    ports:
      - ${WP_PORT}
    image: nginx:latest
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - ${PHPMYADMIN_PORT}

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT}